In [7]:
import torch
import torch.nn as nn


In [15]:
class Model(nn.Module):
  def __init__(self , num_features):

     super(Model, self).__init__()
     self.network = nn.Sequential(
          nn.Linear(num_features , 3),
          nn.ReLU(),
          nn.Linear(3 , 1),
          nn.Sigmoid() )


  def forward(self ,features):

    out = self.network(features)
    return out

features = torch.rand(10,5)
model = Model(features.shape[1])
model(features)

tensor([[0.4781],
        [0.4765],
        [0.4728],
        [0.4733],
        [0.4698],
        [0.4584],
        [0.4731],
        [0.4867],
        [0.4733],
        [0.4642]], grad_fn=<SigmoidBackward0>)

In [9]:
model.layer1.weight

Parameter containing:
tensor([[ 0.3046,  0.4298, -0.2465,  0.1652,  0.3179],
        [-0.3191,  0.0301,  0.1556,  0.2859,  0.3245],
        [ 0.1092,  0.0884, -0.1197,  0.0658,  0.2643]], requires_grad=True)

In [11]:
model.layer2.bias

Parameter containing:
tensor([-0.0051], requires_grad=True)

In [12]:
!pip install torchinfo

In [13]:
from torchinfo import summary

summary(model, input_size=(10, 5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00